import type { Locale } from './types';

export const copy = {
  zh: {
    title: 'Pixel Download',
    subtitle: '公开链接下载器',
    queueTitle: 'Queue List',
    clearWorkspace: '清空工作区',
    emptyQueue: '队列里还没有链接',
    emptyHint: '粘贴 Instagram、Threads 或 TikTok 的公开链接，然后开始解析。',
    addToQueue: '添加队列',
    pasteClipboard: '粘贴剪贴板',
    dropPrompt: '粘贴一个或多条公开链接',
    dropHint: '支持公开帖子、轮播、图集与视频；每行一条更稳。',
    compactPrompt: '继续追加链接',
    compactHint: '已进入批量队列模式。',
    supportedSources: 'SUPPORTED SOURCES',
    publicOnly: 'PUBLIC LINKS ONLY',
    batchReady: 'BATCH ZIP READY',
    supportedBody: 'Instagram / Threads / TikTok',
    supportedMeta: '公开视频、图片、轮播、图集',
    publicBody: '不接入账号、不托管 Cookie',
    publicMeta: '仅处理公开内容与公开分享链接',
    batchBody: 'API 侧流式打包 ZIP',
    batchMeta: '适合多链接整理下载',
    configuration: 'CONFIGURATION',
    resolverSource: '解析线路',
    primaryResolver: '主线路',
    renderResolver: '备用 Render',
    warmRender: '唤醒 Render',
    warmingRender: '唤醒中',
    resolverHintPrimary: '默认走主机房 Cobalt。',
    resolverHintRender: 'Instagram / TikTok 改走 Render 上的备用 Cobalt。',
    renderWarmIdle: '备用解析器会休眠，需要时手动唤醒。',
    renderWarmReady: '备用解析器已唤醒，可以直接解析。',
    contentMode: '内容模式',
    resultMode: '结果模式',
    tiktokMode: 'TikTok 偏好',
    auto: 'Auto',
    videoOnly: 'Video Only',
    imageOnly: 'Image Only',
    singleFiles: 'Single Files',
    zipBundle: 'ZIP',
    preferNoWatermark: '优先无水印',
    resolveQueue: '解析队列',
    downloadZip: '下载 ZIP',
    openDetails: '明细',
    hideDetails: '收起',
    remove: '移除',
    directDownload: '下载',
    selectedAssets: '已选资源',
    settings: '设置',
    services: 'SERVICE NOTES',
    servicesBody: '前端为 Vercel 静态站，下载与 ZIP 由独立 API 提供。',
    servicesMeta: 'Instagram / TikTok 走 Cobalt，Threads 走独立适配层。',
    disclaimer: '仅供下载你有权保存的公开内容。',
    mobileResolve: '解析',
    mobileZip: 'ZIP',
    mobileSettings: '设置',
    state: {
      pending: 'PENDING',
      resolving: 'RESOLVING',
      ready: 'READY',
      error: 'ERROR'
    },
    toast: {
      queueAdded: (count: number) => `已加入 ${count} 条链接。`,
      queueDuplicate: '没有新增链接，队列已包含这些地址。',
      queueEmpty: '先粘贴至少一条链接。',
      resolved: (ok: number, fail: number) => `解析完成：${ok} 成功，${fail} 失败。`,
      zipReady: 'ZIP 已开始下载。',
      zipEmpty: '至少选择一个已解析资源。',
      clipboardFailed: '无法读取剪贴板，请手动粘贴。'
      ,
      renderWarmStarted: '正在唤醒备用 Render，通常需要 20-60 秒。',
      renderWarmReady: '备用 Render 已就绪。',
      renderWarmFailed: '备用 Render 唤醒失败。'
    }
  },
  en: {
    title: 'Pixel Download',
    subtitle: 'Public link downloader',
    queueTitle: 'Queue List',
    clearWorkspace: 'Clear Workspace',
    emptyQueue: 'No links in queue',
    emptyHint: 'Paste public Instagram, Threads, or TikTok links to start resolving.',
    addToQueue: 'Add to Queue',
    pasteClipboard: 'Paste Clipboard',
    dropPrompt: 'Paste one or more public links',
    dropHint: 'Supports public posts, reels, carousels, slideshows, and videos. One URL per line works best.',
    compactPrompt: 'Append more links',
    compactHint: 'Batch queue mode is active.',
    supportedSources: 'SUPPORTED SOURCES',
    publicOnly: 'PUBLIC LINKS ONLY',
    batchReady: 'BATCH ZIP READY',
    supportedBody: 'Instagram / Threads / TikTok',
    supportedMeta: 'Public videos, images, carousels, and slideshows',
    publicBody: 'No login, no cookies, no private profiles',
    publicMeta: 'Only open posts and shareable public links',
    batchBody: 'Server-side ZIP streaming',
    batchMeta: 'Made for collecting multiple links in one pass',
    configuration: 'CONFIGURATION',
    resolverSource: 'Resolver Source',
    primaryResolver: 'Primary',
    renderResolver: 'Render Backup',
    warmRender: 'Wake Render',
    warmingRender: 'Waking',
    resolverHintPrimary: 'Use the primary Cobalt instance.',
    resolverHintRender: 'Route Instagram / TikTok through the Render backup Cobalt.',
    renderWarmIdle: 'The backup resolver can sleep; wake it before use.',
    renderWarmReady: 'The backup resolver is awake and ready.',
    contentMode: 'Content Mode',
    resultMode: 'Result Mode',
    tiktokMode: 'TikTok Preference',
    auto: 'Auto',
    videoOnly: 'Video Only',
    imageOnly: 'Image Only',
    singleFiles: 'Single Files',
    zipBundle: 'ZIP',
    preferNoWatermark: 'Prefer no watermark',
    resolveQueue: 'Resolve Queue',
    downloadZip: 'Download ZIP',
    openDetails: 'Details',
    hideDetails: 'Hide',
    remove: 'Remove',
    directDownload: 'Download',
    selectedAssets: 'Selected Assets',
    settings: 'Settings',
    services: 'SERVICE NOTES',
    servicesBody: 'The frontend is a Vercel static app; downloads and ZIP packaging run through a dedicated API.',
    servicesMeta: 'Instagram / TikTok use Cobalt, while Threads runs on a dedicated adapter.',
    disclaimer: 'Only download public media you have the right to save.',
    mobileResolve: 'Resolve',
    mobileZip: 'ZIP',
    mobileSettings: 'Settings',
    state: {
      pending: 'PENDING',
      resolving: 'RESOLVING',
      ready: 'READY',
      error: 'ERROR'
    },
    toast: {
      queueAdded: (count: number) => `${count} links added to the queue.`,
      queueDuplicate: 'No new links were added; those URLs are already in the queue.',
      queueEmpty: 'Paste at least one link first.',
      resolved: (ok: number, fail: number) => `Resolve finished: ${ok} succeeded, ${fail} failed.`,
      zipReady: 'ZIP download has started.',
      zipEmpty: 'Select at least one resolved asset first.',
      clipboardFailed: 'Clipboard access failed. Paste manually instead.',
      renderWarmStarted: 'Waking the Render backup. This usually takes 20-60 seconds.',
      renderWarmReady: 'The Render backup is ready.',
      renderWarmFailed: 'Failed to wake the Render backup.'
    }
  }
} satisfies Record<Locale, Record<string, unknown>>;
